FizzBuzzProject/FizzBuzzProject/Models/FizzBuzzViewModel.cs
namespace FizzBuzzProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;
    using X.PagedList;

    public class FizzBuzzViewModel
    {
        [Range(1, 1000, ErrorMessage = "Value should be between 1 and 1000")]
        [Required(ErrorMessage = "Please Enter a Value")]
        public int? UserInput { get; set; }

        public IPagedList<string> FizzBuzzNumbers { get; set; }
    }
}

FizzBuzzProject/FizzBuzzProject/Controllers/FizzBuzzController.cs
namespace FizzBuzzProject.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using FizzBuzzProject.Models;
    using FizzBuzzProject.Services;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService service;

        public FizzBuzzController(IFizzBuzzService service)
        {
            this.service = service;
        }

        [HttpGet]
        public ViewResult Index()
        {
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FizzBuzzViewModel fizzBuzzViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }

            return RedirectToAction("GetFizzBuzzNumbersUsingPages", new { fizzBuzzViewModel.UserInput });
        }

        [HttpGet]
        public ViewResult GetFizzBuzzNumbersUsingPages(int userInput, int? page)
        {
            FizzBuzzViewModel fizzBuzzViewModel = new () { UserInput = userInput };
            var numbers =
                service.GetFizzBuzzNumbers(userInput);
            var pageNumber = page ?? 1;
            fizzBuzzViewModel.FizzBuzzNumbers = numbers.ToPagedList(pageNumber, 20);
            return View("Index", fizzBuzzViewModel);
        }
    }
}

// My Notes:
// IEnumerable can be directly converted to PagedList
// Yield can be implemented only with the IEnumerable<> return type.

FizzBuzzProject/FizzBuzzProject/Views/FizzBuzz/Index.cshtml
@model FizzBuzzViewModel
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Fizz Buzz";
}
<form asp-controller="FizzBuzz" asp-action="index" method="post" class="">
    @Html.AntiForgeryToken()
    <div class="form-group row container col-sm-12 text-center">
        <label asp-for="UserInput" class=" col-form-label col-sm-3">Enter a Number</label>
        <div class="col-sm-5 col">
            <input asp-for="UserInput" class="form-control" placeholder="Integer">
        </div>
        <button type="submit" class="btn btn-primary col-sm-1">Enter</button>
        <span asp-validation-for="UserInput" class="text-danger text-center col-sm-3"></span>
    </div>

</form>
<hr>
@{ if (Model?.FizzBuzzNumbers != null)
    {
        <div class="container ">

            @foreach (var fizzBuzzNumber in Model.FizzBuzzNumbers)
            {
                <h4 class="@fizzBuzzNumber">@fizzBuzzNumber</h4>
            }

        </div>
        <div class="cen pagination h4">
            @Html.PagedListPager((IPagedList)Model.FizzBuzzNumbers, page =>
                        Url.Action("GetFizzBuzzNumbersUsingPages", new { page, Model.UserInput }))
        </div>
    }
}

FizzBuzzProject/FizzBuzzProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>
<body>
    <h1 class="text-center">FIZZBUZZ PROJECT</h1>
    <div>
        @RenderBody()
    </div>
</body>
</html>